name: Build and Push to ECR
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  NAME_PREFIX: clo835-a1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push webapp image
        run: |
          WEB_REPO_URI=$(aws ecr describe-repositories --repository-names "${NAME_PREFIX}-webapp" --query 'repositories[0].repositoryUri' --output text)
          docker build --no-cache -t "$WEB_REPO_URI:latest" -f Dockerfile .
          docker push "$WEB_REPO_URI:latest"

      - name: Build & Push mysql image
        run: |
          MYSQL_REPO_URI=$(aws ecr describe-repositories --repository-names "${NAME_PREFIX}-mysql" --query 'repositories[0].repositoryUri' --output text)
          docker build --no-cache -t "$MYSQL_REPO_URI:latest" -f Dockerfile_mysql .
          docker push "$MYSQL_REPO_URI:latest"

